version: 1.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore Source\Splat.Serilog.sln
build:
  project: Source\Splat.Serilog.sln
  verbosity: minimal
after_build:
- ps: >-
    nuget pack Nuget\Splat.Serilog.nuspec -Version $env:APPVEYOR_BUILD_VERSION-Beta

    appveyor PushArtifact Splat.Serilog.$env:APPVEYOR_BUILD_VERSION-Beta.nupkg